# syntax=docker.io/docker/dockerfile:1

FROM node:22-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json* ./
RUN npm ci


# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry during the build.
# ENV NEXT_TELEMETRY_DISABLED=1

ARG BACKEND_BASE_URL
ARG GRAPHQL_ENDPOINT
ARG GRAPHQL_TOKEN
ARG SPIP_RUBRIQUE_PROJETS_ID
ARG SPIP_RUBRIQUE_SERVICES_ID
ARG SPIP_RUBRIQUE_CONTACT_ID
ARG SPIP_ARTICLE_MENTIONS_LEGALES_ID
ARG SPIP_GROUPE_MOTS_METHODOLOGIES_DE_DEVELOPPEMENT_ID
ARG SPIP_GROUPE_MOTS_USAGES_ID
ARG SPIP_GROUPE_MOTS_TECHNOLOGIES_ID
ARG SPIP_GROUPE_MOTS_PARTENAIRES_ID
ARG SPIP_GROUPE_MOTS_UTILISATEURS_ID
ARG SPIP_GROUPE_MOTS_ENTREPRISES_ID
ARG SPIP_RUBRIQUE_CONTACT_ARTICLE_URBAN_LAB_ID
ARG SPIP_RUBRIQUE_CONTACT_ARTICLE_BUREAUX_ADMINISTRATIFS_ID
ARG SPIP_RUBRIQUE_CONTACT_ARTICLE_NOUS_JOINDRE_ID
ARG SPIP_RUBRIQUE_CONTACT_ARTICLE_LACLASSE_ID
ARG SPIP_RUBRIQUE_CONTACT_ARTICLE_RESEAUX_SOCIAUX_ID

ENV BACKEND_BASE_URL=$BACKEND_BASE_URL
ENV GRAPHQL_ENDPOINT=$GRAPHQL_ENDPOINT
ENV GRAPHQL_TOKEN=$GRAPHQL_TOKEN
ENV SPIP_RUBRIQUE_PROJETS_ID=$SPIP_RUBRIQUE_PROJETS_ID
ENV SPIP_RUBRIQUE_SERVICES_ID=$SPIP_RUBRIQUE_SERVICES_ID
ENV SPIP_RUBRIQUE_CONTACT_ID=$SPIP_RUBRIQUE_CONTACT_ID
ENV SPIP_ARTICLE_MENTIONS_LEGALES_ID=$SPIP_ARTICLE_MENTIONS_LEGALES_ID
ENV SPIP_GROUPE_MOTS_METHODOLOGIES_DE_DEVELOPPEMENT_ID=$SPIP_GROUPE_MOTS_METHODOLOGIES_DE_DEVELOPPEMENT_ID
ENV SPIP_GROUPE_MOTS_USAGES_ID=$SPIP_GROUPE_MOTS_USAGES_ID
ENV SPIP_GROUPE_MOTS_TECHNOLOGIES_ID=$SPIP_GROUPE_MOTS_TECHNOLOGIES_ID
ENV SPIP_GROUPE_MOTS_PARTENAIRES_ID=$SPIP_GROUPE_MOTS_PARTENAIRES_ID
ENV SPIP_GROUPE_MOTS_UTILISATEURS_ID=$SPIP_GROUPE_MOTS_UTILISATEURS_ID
ENV SPIP_GROUPE_MOTS_ENTREPRISES_ID=$SPIP_GROUPE_MOTS_ENTREPRISES_ID
ENV SPIP_RUBRIQUE_CONTACT_ARTICLE_URBAN_LAB_ID=$SPIP_RUBRIQUE_CONTACT_ARTICLE_URBAN_LAB_ID
ENV SPIP_RUBRIQUE_CONTACT_ARTICLE_BUREAUX_ADMINISTRATIFS_ID=$SPIP_RUBRIQUE_CONTACT_ARTICLE_BUREAUX_ADMINISTRATIFS_ID
ENV SPIP_RUBRIQUE_CONTACT_ARTICLE_NOUS_JOINDRE_ID=$SPIP_RUBRIQUE_CONTACT_ARTICLE_NOUS_JOINDRE_ID
ENV SPIP_RUBRIQUE_CONTACT_ARTICLE_LACLASSE_ID=$SPIP_RUBRIQUE_CONTACT_ARTICLE_LACLASSE_ID
ENV SPIP_RUBRIQUE_CONTACT_ARTICLE_RESEAUX_SOCIAUX_ID=$SPIP_RUBRIQUE_CONTACT_ARTICLE_RESEAUX_SOCIAUX_ID


RUN echo $BACKEND_BASE_URL
RUN echo $GRAPHQL_ENDPOINT
RUN echo $GRAPHQL_TOKEN
RUN echo $SPIP_RUBRIQUE_PROJETS_ID
RUN echo $SPIP_RUBRIQUE_SERVICES_ID
RUN echo $SPIP_RUBRIQUE_CONTACT_ID
RUN echo $SPIP_ARTICLE_MENTIONS_LEGALES_ID
RUN echo $SPIP_GROUPE_MOTS_METHODOLOGIES_DE_DEVELOPPEMENT_ID
RUN echo $SPIP_GROUPE_MOTS_USAGES_ID
RUN echo $SPIP_GROUPE_MOTS_TECHNOLOGIES_ID
RUN echo $SPIP_GROUPE_MOTS_PARTENAIRES_ID
RUN echo $SPIP_GROUPE_MOTS_UTILISATEURS_ID
RUN echo $SPIP_GROUPE_MOTS_ENTREPRISES_ID
RUN echo $SPIP_RUBRIQUE_CONTACT_ARTICLE_URBAN_LAB_ID
RUN echo $SPIP_RUBRIQUE_CONTACT_ARTICLE_BUREAUX_ADMINISTRATIFS_ID
RUN echo $SPIP_RUBRIQUE_CONTACT_ARTICLE_NOUS_JOINDRE_ID
RUN echo $SPIP_RUBRIQUE_CONTACT_ARTICLE_LACLASSE_ID
RUN echo $SPIP_RUBRIQUE_CONTACT_ARTICLE_RESEAUX_SOCIAUX_ID

RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

# Uncomment the following line in case you want to disable telemetry during runtime.
# ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

ENV PORT=3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/config/next-config-js/output
ENV HOSTNAME="0.0.0.0"
CMD ["node", "server.js"]