/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n": typeof types.PaginationFieldsFragmentDoc,
    "\n    fragment rubriqueBasicInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n    }\n": typeof types.RubriqueBasicInformationFieldsFragmentDoc,
    "\n    fragment rubriqueFullInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n\n        titre_section_supplementaire_1\n        texte_section_supplementaire_1\n        titre_section_supplementaire_2\n        texte_section_supplementaire_2\n        titre_section_stades_dev\n        texte_section_stades_dev\n        data_section_stades_dev\n        titre_section_chiffres_cles\n        texte_section_chiffres_cles\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n": typeof types.RubriqueFullInformationFieldsFragmentDoc,
    "\n    fragment articleBasicInformationFields on Article {\n        id\n        identifiant\n        titre\n        date\n        logo\n        isprototype\n        rubrique {\n            id\n            titre\n        }\n    }\n": typeof types.ArticleBasicInformationFieldsFragmentDoc,
    "\n    fragment articleFullInformationFields on Article {\n        id\n        identifiant\n        titre\n        texte\n        logo\n        date\n        isprototype\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n": typeof types.ArticleFullInformationFieldsFragmentDoc,
    "\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n        description_title_third\n        description_third\n        descr_tech_technique\n        descr_tech_devices\n        descr_tech_framework\n        descr_tech_depot\n        descr_tech_licence\n\n        #Get all images\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n": typeof types.PrototypeInformationFieldsFragmentDoc,
    "\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        identifiant\n        titre\n    }\n": typeof types.AuteurBasicInformationFieldsFragmentDoc,
    "\n    fragment auteurFullInformationFields on Auteur {\n        id\n        identifiant\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n": typeof types.AuteurFullInformationFieldsFragmentDoc,
    "\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n": typeof types.MotBasicInformationFieldsFragmentDoc,
    "\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n": typeof types.DocumentBasicInformationFieldsFragmentDoc,
    "\n    fragment documentFullInformationFields on Document {\n        id\n        media\n        fichier\n        largeur\n        hauteur\n        alt\n    }\n": typeof types.DocumentFullInformationFieldsFragmentDoc,
    "\n    fragment listProjetsFields on Rubrique{\n        id\n        identifiant\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.ListProjetsFieldsFragmentDoc,
    "\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        identifiant\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n": typeof types.MotsAndGroupeMotsFieldsFragmentDoc,
    "\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n": typeof types.ArticleDocument,
    "\n    query ArticleAndPrototypeByIdentifiant($identifiant: String!) {\n        getArticle(identifiant: $identifiant) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n": typeof types.ArticleAndPrototypeByIdentifiantDocument,
    "\n    query RubriquePresentation(\n            $id: Int!,\n            $withRubriqueFullInformation: Boolean! = false\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n        }\n    }\n": typeof types.RubriquePresentationDocument,
    "\n    query RubriqueWithArticles(\n            $id: Int!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n": typeof types.RubriqueWithArticlesDocument,
    "\n    query RubriqueWithArticlesByIdentifiant(\n            $identifiant: String!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(identifiant: $identifiant) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n": typeof types.RubriqueWithArticlesByIdentifiantDocument,
    "\n    query MotByIdentifiant($identifiant: String!) {\n        getMot(identifiant: $identifiant) {\n            ...motBasicInformationFields\n        }\n    }\n": typeof types.MotByIdentifiantDocument,
    "\n    query AuteurByIdentifiant($identifiant: String!) {\n        getAuteur(identifiant: $identifiant) {\n            ...auteurFullInformationFields\n        }\n    }\n": typeof types.AuteurByIdentifiantDocument,
    "\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false\n        ) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n": typeof types.SearchDocument,
    "\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $withAuteurs: Boolean = false,\n            $pagination: Int = 5000,\n            $page: Int = 1\n        ) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n    }\n": typeof types.AllProjectsAndNestedCollectionsDocument,
    "\n    query ActiveAuthors(\n        $idRubriqueEquipe: Int!\n    ) {\n        getRubrique(id: $idRubriqueEquipe) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.ActiveAuthorsDocument,
    "\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n": typeof types.MotsFromGroupeMotsDocument,
    "\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4,\n        $idRubriqueServices: Int!,\n        $idArticleMission: Int!,\n        $idArticlePresentationErasme: Int!,\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n        mission: getArticle(id: $idArticleMission) {\n            ...articleFullInformationFields\n        }\n        presentationErasme: getArticle(id: $idArticlePresentationErasme) {\n            ...articleFullInformationFields\n        }\n    }\n": typeof types.HomepageDocument,
};
const documents: Documents = {
    "\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n": types.PaginationFieldsFragmentDoc,
    "\n    fragment rubriqueBasicInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n    }\n": types.RubriqueBasicInformationFieldsFragmentDoc,
    "\n    fragment rubriqueFullInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n\n        titre_section_supplementaire_1\n        texte_section_supplementaire_1\n        titre_section_supplementaire_2\n        texte_section_supplementaire_2\n        titre_section_stades_dev\n        texte_section_stades_dev\n        data_section_stades_dev\n        titre_section_chiffres_cles\n        texte_section_chiffres_cles\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n": types.RubriqueFullInformationFieldsFragmentDoc,
    "\n    fragment articleBasicInformationFields on Article {\n        id\n        identifiant\n        titre\n        date\n        logo\n        isprototype\n        rubrique {\n            id\n            titre\n        }\n    }\n": types.ArticleBasicInformationFieldsFragmentDoc,
    "\n    fragment articleFullInformationFields on Article {\n        id\n        identifiant\n        titre\n        texte\n        logo\n        date\n        isprototype\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n": types.ArticleFullInformationFieldsFragmentDoc,
    "\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n        description_title_third\n        description_third\n        descr_tech_technique\n        descr_tech_devices\n        descr_tech_framework\n        descr_tech_depot\n        descr_tech_licence\n\n        #Get all images\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n": types.PrototypeInformationFieldsFragmentDoc,
    "\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        identifiant\n        titre\n    }\n": types.AuteurBasicInformationFieldsFragmentDoc,
    "\n    fragment auteurFullInformationFields on Auteur {\n        id\n        identifiant\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n": types.AuteurFullInformationFieldsFragmentDoc,
    "\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n": types.MotBasicInformationFieldsFragmentDoc,
    "\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n": types.DocumentBasicInformationFieldsFragmentDoc,
    "\n    fragment documentFullInformationFields on Document {\n        id\n        media\n        fichier\n        largeur\n        hauteur\n        alt\n    }\n": types.DocumentFullInformationFieldsFragmentDoc,
    "\n    fragment listProjetsFields on Rubrique{\n        id\n        identifiant\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.ListProjetsFieldsFragmentDoc,
    "\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        identifiant\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n": types.MotsAndGroupeMotsFieldsFragmentDoc,
    "\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n": types.ArticleDocument,
    "\n    query ArticleAndPrototypeByIdentifiant($identifiant: String!) {\n        getArticle(identifiant: $identifiant) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n": types.ArticleAndPrototypeByIdentifiantDocument,
    "\n    query RubriquePresentation(\n            $id: Int!,\n            $withRubriqueFullInformation: Boolean! = false\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n        }\n    }\n": types.RubriquePresentationDocument,
    "\n    query RubriqueWithArticles(\n            $id: Int!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n": types.RubriqueWithArticlesDocument,
    "\n    query RubriqueWithArticlesByIdentifiant(\n            $identifiant: String!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(identifiant: $identifiant) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n": types.RubriqueWithArticlesByIdentifiantDocument,
    "\n    query MotByIdentifiant($identifiant: String!) {\n        getMot(identifiant: $identifiant) {\n            ...motBasicInformationFields\n        }\n    }\n": types.MotByIdentifiantDocument,
    "\n    query AuteurByIdentifiant($identifiant: String!) {\n        getAuteur(identifiant: $identifiant) {\n            ...auteurFullInformationFields\n        }\n    }\n": types.AuteurByIdentifiantDocument,
    "\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false\n        ) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n": types.SearchDocument,
    "\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $withAuteurs: Boolean = false,\n            $pagination: Int = 5000,\n            $page: Int = 1\n        ) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n    }\n": types.AllProjectsAndNestedCollectionsDocument,
    "\n    query ActiveAuthors(\n        $idRubriqueEquipe: Int!\n    ) {\n        getRubrique(id: $idRubriqueEquipe) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.ActiveAuthorsDocument,
    "\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n": types.MotsFromGroupeMotsDocument,
    "\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4,\n        $idRubriqueServices: Int!,\n        $idArticleMission: Int!,\n        $idArticlePresentationErasme: Int!,\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n        mission: getArticle(id: $idArticleMission) {\n            ...articleFullInformationFields\n        }\n        presentationErasme: getArticle(id: $idArticlePresentationErasme) {\n            ...articleFullInformationFields\n        }\n    }\n": types.HomepageDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n"): (typeof documents)["\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment rubriqueBasicInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n    }\n"): (typeof documents)["\n    fragment rubriqueBasicInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment rubriqueFullInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n\n        titre_section_supplementaire_1\n        texte_section_supplementaire_1\n        titre_section_supplementaire_2\n        texte_section_supplementaire_2\n        titre_section_stades_dev\n        texte_section_stades_dev\n        data_section_stades_dev\n        titre_section_chiffres_cles\n        texte_section_chiffres_cles\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment rubriqueFullInformationFields on Rubrique {\n        id\n        identifiant\n        titre\n        texte\n        logo\n\n        titre_section_supplementaire_1\n        texte_section_supplementaire_1\n        titre_section_supplementaire_2\n        texte_section_supplementaire_2\n        titre_section_stades_dev\n        texte_section_stades_dev\n        data_section_stades_dev\n        titre_section_chiffres_cles\n        texte_section_chiffres_cles\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment articleBasicInformationFields on Article {\n        id\n        identifiant\n        titre\n        date\n        logo\n        isprototype\n        rubrique {\n            id\n            titre\n        }\n    }\n"): (typeof documents)["\n    fragment articleBasicInformationFields on Article {\n        id\n        identifiant\n        titre\n        date\n        logo\n        isprototype\n        rubrique {\n            id\n            titre\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment articleFullInformationFields on Article {\n        id\n        identifiant\n        titre\n        texte\n        logo\n        date\n        isprototype\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment articleFullInformationFields on Article {\n        id\n        identifiant\n        titre\n        texte\n        logo\n        date\n        isprototype\n\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n        description_title_third\n        description_third\n        descr_tech_technique\n        descr_tech_devices\n        descr_tech_framework\n        descr_tech_depot\n        descr_tech_licence\n\n        #Get all images\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n        description_title_third\n        description_third\n        descr_tech_technique\n        descr_tech_devices\n        descr_tech_framework\n        descr_tech_depot\n        descr_tech_licence\n\n        #Get all images\n        documents(pagination: 100, where:\"media=image\") {\n            result {\n                ...documentFullInformationFields\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        identifiant\n        titre\n    }\n"): (typeof documents)["\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        identifiant\n        titre\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment auteurFullInformationFields on Auteur {\n        id\n        identifiant\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n"): (typeof documents)["\n    fragment auteurFullInformationFields on Auteur {\n        id\n        identifiant\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n"): (typeof documents)["\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n"): (typeof documents)["\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment documentFullInformationFields on Document {\n        id\n        media\n        fichier\n        largeur\n        hauteur\n        alt\n    }\n"): (typeof documents)["\n    fragment documentFullInformationFields on Document {\n        id\n        media\n        fichier\n        largeur\n        hauteur\n        alt\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment listProjetsFields on Rubrique{\n        id\n        identifiant\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment listProjetsFields on Rubrique{\n        id\n        identifiant\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        identifiant\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n"): (typeof documents)["\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        identifiant\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n"): (typeof documents)["\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query ArticleAndPrototypeByIdentifiant($identifiant: String!) {\n        getArticle(identifiant: $identifiant) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n"): (typeof documents)["\n    query ArticleAndPrototypeByIdentifiant($identifiant: String!) {\n        getArticle(identifiant: $identifiant) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query RubriquePresentation(\n            $id: Int!,\n            $withRubriqueFullInformation: Boolean! = false\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n        }\n    }\n"): (typeof documents)["\n    query RubriquePresentation(\n            $id: Int!,\n            $withRubriqueFullInformation: Boolean! = false\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query RubriqueWithArticles(\n            $id: Int!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query RubriqueWithArticles(\n            $id: Int!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(id: $id) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query RubriqueWithArticlesByIdentifiant(\n            $identifiant: String!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(identifiant: $identifiant) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query RubriqueWithArticlesByIdentifiant(\n            $identifiant: String!,\n            $withArticleFullInformation: Boolean! = false,\n            $withRubriqueFullInformation: Boolean! = false,\n        ) {\n        getRubrique(identifiant: $identifiant) {\n            ...rubriqueBasicInformationFields @skip(if: $withRubriqueFullInformation) \n            ...rubriqueFullInformationFields @include(if: $withRubriqueFullInformation)\n\n            articles(pagination: 500, orderby: [\"date_DESC\"]) {\n                result {\n                    ...articleBasicInformationFields @skip(if: $withArticleFullInformation)\n                    ...articleFullInformationFields @include(if: $withArticleFullInformation)\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query MotByIdentifiant($identifiant: String!) {\n        getMot(identifiant: $identifiant) {\n            ...motBasicInformationFields\n        }\n    }\n"): (typeof documents)["\n    query MotByIdentifiant($identifiant: String!) {\n        getMot(identifiant: $identifiant) {\n            ...motBasicInformationFields\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query AuteurByIdentifiant($identifiant: String!) {\n        getAuteur(identifiant: $identifiant) {\n            ...auteurFullInformationFields\n        }\n    }\n"): (typeof documents)["\n    query AuteurByIdentifiant($identifiant: String!) {\n        getAuteur(identifiant: $identifiant) {\n            ...auteurFullInformationFields\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false\n        ) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false\n        ) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $withAuteurs: Boolean = false,\n            $pagination: Int = 5000,\n            $page: Int = 1\n        ) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n    }\n"): (typeof documents)["\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $withAuteurs: Boolean = false,\n            $pagination: Int = 5000,\n            $page: Int = 1\n        ) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query ActiveAuthors(\n        $idRubriqueEquipe: Int!\n    ) {\n        getRubrique(id: $idRubriqueEquipe) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query ActiveAuthors(\n        $idRubriqueEquipe: Int!\n    ) {\n        getRubrique(id: $idRubriqueEquipe) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4,\n        $idRubriqueServices: Int!,\n        $idArticleMission: Int!,\n        $idArticlePresentationErasme: Int!,\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n        mission: getArticle(id: $idArticleMission) {\n            ...articleFullInformationFields\n        }\n        presentationErasme: getArticle(id: $idArticlePresentationErasme) {\n            ...articleFullInformationFields\n        }\n    }\n"): (typeof documents)["\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4,\n        $idRubriqueServices: Int!,\n        $idArticleMission: Int!,\n        $idArticlePresentationErasme: Int!,\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n        mission: getArticle(id: $idArticleMission) {\n            ...articleFullInformationFields\n        }\n        presentationErasme: getArticle(id: $idArticlePresentationErasme) {\n            ...articleFullInformationFields\n        }\n    }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;