/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n": typeof types.PaginationFieldsFragmentDoc,
    "\n    fragment rubriqueInformationFields on Rubrique {\n        id\n        titre\n        texte\n        logo\n    }\n": typeof types.RubriqueInformationFieldsFragmentDoc,
    "\n    fragment articleBasicInformationFields on Article {\n        id\n        titre\n        date\n        logo\n        isprototype\n    }\n": typeof types.ArticleBasicInformationFieldsFragmentDoc,
    "\n    fragment articleFullInformationFields on Article {\n        id\n        titre\n        texte\n        logo\n        date\n        isprototype\n    }\n": typeof types.ArticleFullInformationFieldsFragmentDoc,
    "\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n    }\n": typeof types.PrototypeInformationFieldsFragmentDoc,
    "\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        titre\n    }\n": typeof types.AuteurBasicInformationFieldsFragmentDoc,
    "\n    fragment auteurFullInformationFields on Auteur {\n        id\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n": typeof types.AuteurFullInformationFieldsFragmentDoc,
    "\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n": typeof types.MotBasicInformationFieldsFragmentDoc,
    "\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n": typeof types.DocumentBasicInformationFieldsFragmentDoc,
    "\n    fragment listProjetsFields on Rubrique{\n        id\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(where: $whereAuteurs, pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.ListProjetsFieldsFragmentDoc,
    "\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n": typeof types.MotsAndGroupeMotsFieldsFragmentDoc,
    "\n    query ServicesRubrique($id: Int!) {\n        getRubrique(id: $id) {\n            logo\n            articles {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n": typeof types.ServicesRubriqueDocument,
    "\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n": typeof types.ArticleDocument,
    "\n    query ArticleAndPrototype($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n": typeof types.ArticleAndPrototypeDocument,
    "\n    query RubriquePresentation($id: Int!) {\n        getRubrique(id: $id) {\n            id\n            titre\n            texte\n            logo\n        }\n    }\n": typeof types.RubriquePresentationDocument,
    "\n    query DynamicPage($id: Int!) {\n        getRubrique(id: $id) {\n            ...rubriqueInformationFields\n\n            articles(pagination: 100) {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n": typeof types.DynamicPageDocument,
    "\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!]) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n                ...on Document {\n                    ...documentBasicInformationFields\n                }\n            }\n        }\n    }\n": typeof types.SearchDocument,
    "\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $idGroupeMotsForFilter: Int!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!],\n            $idAuteur: Int = 0,\n            $pagination: Int = 5000,\n            $page: Int = 1\n            $withPartenaires: Boolean = false,\n            $idPartenaire: Int = 0) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n\n        getGroupe_mots(id: $idGroupeMotsForFilter){\n            id\n            titre\n            mots (pagination: $pagination) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n        getAuteur(id: $idAuteur) @include(if: $withAuteurs) {\n            ...auteurFullInformationFields\n        }\n        getMot(id: $idPartenaire) @include(if: $withPartenaires){\n            ...motBasicInformationFields\n        }\n    }\n": typeof types.AllProjectsAndNestedCollectionsDocument,
    "\n    query ActiveAuthors(\n        $idRubriqueTrombinoscope: Int!\n    ) {\n        getRubrique(id: $idRubriqueTrombinoscope) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            id\n                            titre\n                        }\n                    }\n                }\n            }\n        }\n    }\n": typeof types.ActiveAuthorsDocument,
    "\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n": typeof types.MotsFromGroupeMotsDocument,
    "\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4\n        $idRubriqueServices: Int!\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n": typeof types.HomepageDocument,
};
const documents: Documents = {
    "\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n": types.PaginationFieldsFragmentDoc,
    "\n    fragment rubriqueInformationFields on Rubrique {\n        id\n        titre\n        texte\n        logo\n    }\n": types.RubriqueInformationFieldsFragmentDoc,
    "\n    fragment articleBasicInformationFields on Article {\n        id\n        titre\n        date\n        logo\n        isprototype\n    }\n": types.ArticleBasicInformationFieldsFragmentDoc,
    "\n    fragment articleFullInformationFields on Article {\n        id\n        titre\n        texte\n        logo\n        date\n        isprototype\n    }\n": types.ArticleFullInformationFieldsFragmentDoc,
    "\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n    }\n": types.PrototypeInformationFieldsFragmentDoc,
    "\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        titre\n    }\n": types.AuteurBasicInformationFieldsFragmentDoc,
    "\n    fragment auteurFullInformationFields on Auteur {\n        id\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n": types.AuteurFullInformationFieldsFragmentDoc,
    "\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n": types.MotBasicInformationFieldsFragmentDoc,
    "\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n": types.DocumentBasicInformationFieldsFragmentDoc,
    "\n    fragment listProjetsFields on Rubrique{\n        id\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(where: $whereAuteurs, pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.ListProjetsFieldsFragmentDoc,
    "\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n": types.MotsAndGroupeMotsFieldsFragmentDoc,
    "\n    query ServicesRubrique($id: Int!) {\n        getRubrique(id: $id) {\n            logo\n            articles {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n": types.ServicesRubriqueDocument,
    "\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n": types.ArticleDocument,
    "\n    query ArticleAndPrototype($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n": types.ArticleAndPrototypeDocument,
    "\n    query RubriquePresentation($id: Int!) {\n        getRubrique(id: $id) {\n            id\n            titre\n            texte\n            logo\n        }\n    }\n": types.RubriquePresentationDocument,
    "\n    query DynamicPage($id: Int!) {\n        getRubrique(id: $id) {\n            ...rubriqueInformationFields\n\n            articles(pagination: 100) {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n": types.DynamicPageDocument,
    "\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!]) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n                ...on Document {\n                    ...documentBasicInformationFields\n                }\n            }\n        }\n    }\n": types.SearchDocument,
    "\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $idGroupeMotsForFilter: Int!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!],\n            $idAuteur: Int = 0,\n            $pagination: Int = 5000,\n            $page: Int = 1\n            $withPartenaires: Boolean = false,\n            $idPartenaire: Int = 0) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n\n        getGroupe_mots(id: $idGroupeMotsForFilter){\n            id\n            titre\n            mots (pagination: $pagination) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n        getAuteur(id: $idAuteur) @include(if: $withAuteurs) {\n            ...auteurFullInformationFields\n        }\n        getMot(id: $idPartenaire) @include(if: $withPartenaires){\n            ...motBasicInformationFields\n        }\n    }\n": types.AllProjectsAndNestedCollectionsDocument,
    "\n    query ActiveAuthors(\n        $idRubriqueTrombinoscope: Int!\n    ) {\n        getRubrique(id: $idRubriqueTrombinoscope) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            id\n                            titre\n                        }\n                    }\n                }\n            }\n        }\n    }\n": types.ActiveAuthorsDocument,
    "\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n": types.MotsFromGroupeMotsDocument,
    "\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4\n        $idRubriqueServices: Int!\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n": types.HomepageDocument,
};

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = gql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function gql(source: string): unknown;

/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n"): (typeof documents)["\n    fragment paginationFields on Pagination {\n        currentPage\n        totalPages\n        hasNextPage\n        hasPreviousPage\n        totalItems\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment rubriqueInformationFields on Rubrique {\n        id\n        titre\n        texte\n        logo\n    }\n"): (typeof documents)["\n    fragment rubriqueInformationFields on Rubrique {\n        id\n        titre\n        texte\n        logo\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment articleBasicInformationFields on Article {\n        id\n        titre\n        date\n        logo\n        isprototype\n    }\n"): (typeof documents)["\n    fragment articleBasicInformationFields on Article {\n        id\n        titre\n        date\n        logo\n        isprototype\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment articleFullInformationFields on Article {\n        id\n        titre\n        texte\n        logo\n        date\n        isprototype\n    }\n"): (typeof documents)["\n    fragment articleFullInformationFields on Article {\n        id\n        titre\n        texte\n        logo\n        date\n        isprototype\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n    }\n"): (typeof documents)["\n    fragment prototypeInformationFields on Article {\n        description_title\n        description\n        description_title_second\n        description_second\n        chiffres_cles\n        description_lateral_title\n        description_lateral\n        developpement\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        titre\n    }\n"): (typeof documents)["\n    fragment auteurBasicInformationFields on Auteur {\n        id\n        titre\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment auteurFullInformationFields on Auteur {\n        id\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n"): (typeof documents)["\n    fragment auteurFullInformationFields on Auteur {\n        id\n        titre\n        logo\n        descriptif\n        email\n        auteur_compte_linkedin\n        auteur_compte_twitter\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n"): (typeof documents)["\n    fragment motBasicInformationFields on Mot {\n        id\n        titre\n        logo\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n"): (typeof documents)["\n    fragment documentBasicInformationFields on Document {\n        id\n        titre\n        media\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment listProjetsFields on Rubrique{\n        id\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(where: $whereAuteurs, pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    fragment listProjetsFields on Rubrique{\n        id\n        titre\n        texte\n        date\n        articles(orderby: $articlesInRubriqueOrderBy, pagination: $pagination) {\n            ...on ArticlePagination {\n                pagination {\n                    ...paginationFields\n                }\n                result {\n                    ...articleBasicInformationFields\n                \n                    mots(pagination: $pagination) {\n                        result {\n                            ...motsAndGroupeMotsFields\n                        }\n                    }\n\n                    auteurs(where: $whereAuteurs, pagination: $pagination) @include(if: $withAuteurs) {\n                        result {\n                            ...auteurBasicInformationFields\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n"): (typeof documents)["\n    fragment motsAndGroupeMotsFields on Mot {\n        id\n        titre\n        groupe {\n            id\n            titre\n        }\n    }    \n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query ServicesRubrique($id: Int!) {\n        getRubrique(id: $id) {\n            logo\n            articles {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query ServicesRubrique($id: Int!) {\n        getRubrique(id: $id) {\n            logo\n            articles {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n"): (typeof documents)["\n    query Article($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query ArticleAndPrototype($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n"): (typeof documents)["\n    query ArticleAndPrototype($id: Int!) {\n        getArticle(id: $id) {\n            ...articleFullInformationFields\n            \n            ...prototypeInformationFields\n\n            #We want to fetch all 'mots'\n            mots(pagination: 100) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n\n            auteurs {\n                result {\n                    ...auteurBasicInformationFields\n                }  \n            }\n            \n            rubrique {\n                logo\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query RubriquePresentation($id: Int!) {\n        getRubrique(id: $id) {\n            id\n            titre\n            texte\n            logo\n        }\n    }\n"): (typeof documents)["\n    query RubriquePresentation($id: Int!) {\n        getRubrique(id: $id) {\n            id\n            titre\n            texte\n            logo\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query DynamicPage($id: Int!) {\n        getRubrique(id: $id) {\n            ...rubriqueInformationFields\n\n            articles(pagination: 100) {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query DynamicPage($id: Int!) {\n        getRubrique(id: $id) {\n            ...rubriqueInformationFields\n\n            articles(pagination: 100) {\n                result {\n                    ...articleFullInformationFields\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!]) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n                ...on Document {\n                    ...documentBasicInformationFields\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query Search(\n            $texte: String!, \n            $generalOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!], \n            $pagination: Int = 5000, \n            $page: Int = 1, \n            $where: String!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!]) {\n        recherche(texte: $texte, orderby: $generalOrderBy, pagination: $pagination, page: $page, where: $where) {\n            result {\n                ...on Rubrique {\n                    ...listProjetsFields\n                }\n                ...on Article {\n                    ...articleBasicInformationFields\n                }\n                ...on Document {\n                    ...documentBasicInformationFields\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $idGroupeMotsForFilter: Int!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!],\n            $idAuteur: Int = 0,\n            $pagination: Int = 5000,\n            $page: Int = 1\n            $withPartenaires: Boolean = false,\n            $idPartenaire: Int = 0) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n\n        getGroupe_mots(id: $idGroupeMotsForFilter){\n            id\n            titre\n            mots (pagination: $pagination) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n        getAuteur(id: $idAuteur) @include(if: $withAuteurs) {\n            ...auteurFullInformationFields\n        }\n        getMot(id: $idPartenaire) @include(if: $withPartenaires){\n            ...motBasicInformationFields\n        }\n    }\n"): (typeof documents)["\n    query AllProjectsAndNestedCollections(\n            $whereRubriques: [String!],\n            $rubriquesOrderBy: [String!],\n            $articlesInRubriqueOrderBy: [String!],\n            $idGroupeMotsForFilter: Int!,\n            $withAuteurs: Boolean = false,\n            $whereAuteurs: [String!],\n            $idAuteur: Int = 0,\n            $pagination: Int = 5000,\n            $page: Int = 1\n            $withPartenaires: Boolean = false,\n            $idPartenaire: Int = 0) {\n        rubriques(where: $whereRubriques, orderby: $rubriquesOrderBy, pagination: $pagination, page: $page) {\n            pagination {\n                ...paginationFields\n            }\n            result {\n                ...listProjetsFields\n            }\n        }\n\n        getGroupe_mots(id: $idGroupeMotsForFilter){\n            id\n            titre\n            mots (pagination: $pagination) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n        getAuteur(id: $idAuteur) @include(if: $withAuteurs) {\n            ...auteurFullInformationFields\n        }\n        getMot(id: $idPartenaire) @include(if: $withPartenaires){\n            ...motBasicInformationFields\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query ActiveAuthors(\n        $idRubriqueTrombinoscope: Int!\n    ) {\n        getRubrique(id: $idRubriqueTrombinoscope) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            id\n                            titre\n                        }\n                    }\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query ActiveAuthors(\n        $idRubriqueTrombinoscope: Int!\n    ) {\n        getRubrique(id: $idRubriqueTrombinoscope) {\n            id\n            titre\n            texte\n            logo\n\n            articles(pagination: 100) {\n                result {\n                    id\n                    auteurs {\n                        result {\n                            id\n                            titre\n                        }\n                    }\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query MotsFromGroupeMots(\n        $idGroupeMots: Int!\n    ){\n        getGroupe_mots(id: $idGroupeMots){\n            id\n            titre\n\n            mots(pagination: 500) {\n                result {\n                    ...motsAndGroupeMotsFields\n                }\n            }\n        }\n    }\n"];
/**
 * The gql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function gql(source: "\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4\n        $idRubriqueServices: Int!\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n"): (typeof documents)["\n    query Homepage(\n        $idMotActus: Int!,\n        $numberOfActus: Int = 4\n        $idRubriqueServices: Int!\n    ){\n        getMot(id: $idMotActus) {\n            id\n            articles(orderby: [\"date_DESC\"], pagination: $numberOfActus) {\n                result{\n                    ...articleFullInformationFields\n                }\n            }\n        }\n        articles(pagination: 5000) {\n            result {\n                id\n            }\n        }\n        getRubrique(id: $idRubriqueServices) {\n            id\n            articles {\n                result {\n                    ...articleBasicInformationFields\n                }\n            }\n        }\n    }\n"];

export function gql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;