name: Build and Push Docker Images

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          tags: erasme/erasme.org-v2-front:${{ github.ref == 'refs/heads/main' && 'latest' || 'dev' }} , erasme/erasme.org-v2-front:${{ github.sha }}
          build-args: |
            BACKEND_BASE_URL=${{ vars.BACKEND_BASE_URL }}
            GRAPHQL_ENDPOINT=${{ vars.GRAPHQL_ENDPOINT }}
            GRAPHQL_TOKEN=${{ secrets.GRAPHQL_TOKEN }}
            SPIP_RUBRIQUE_PROJETS_ID=${{ vars.SPIP_RUBRIQUE_PROJETS_ID }}
            SPIP_RUBRIQUE_SERVICES_ID=${{ vars.SPIP_RUBRIQUE_SERVICES_ID }}
            SPIP_RUBRIQUE_CONTACT_ID=${{ vars.SPIP_RUBRIQUE_CONTACT_ID }}
            SPIP_ARTICLE_MENTIONS_LEGALES_ID=${{ vars.SPIP_ARTICLE_MENTIONS_LEGALES_ID }}
            SPIP_GROUPE_MOTS_METHODOLOGIES_DE_DEVELOPPEMENT_ID=${{ vars.SPIP_GROUPE_MOTS_METHODOLOGIES_DE_DEVELOPPEMENT_ID }}
            SPIP_GROUPE_MOTS_USAGES_ID=${{ vars.SPIP_GROUPE_MOTS_USAGES_ID }}
            SPIP_GROUPE_MOTS_TECHNOLOGIES_ID=${{ vars.SPIP_GROUPE_MOTS_TECHNOLOGIES_ID }}
            SPIP_GROUPE_MOTS_PARTENAIRES_ID=${{ vars.SPIP_GROUPE_MOTS_PARTENAIRES_ID }}
            SPIP_GROUPE_MOTS_UTILISATEURS_ID=${{ vars.SPIP_GROUPE_MOTS_UTILISATEURS_ID }}
            SPIP_GROUPE_MOTS_ENTREPRISES_ID=${{ vars.SPIP_GROUPE_MOTS_ENTREPRISES_ID }}
            SPIP_RUBRIQUE_CONTACT_ARTICLE_URBAN_LAB_ID=${{ vars.SPIP_RUBRIQUE_CONTACT_ARTICLE_URBAN_LAB_ID }}
            SPIP_RUBRIQUE_CONTACT_ARTICLE_BUREAUX_ADMINISTRATIFS_ID=${{ vars.SPIP_RUBRIQUE_CONTACT_ARTICLE_BUREAUX_ADMINISTRATIFS_ID }}
            SPIP_RUBRIQUE_CONTACT_ARTICLE_NOUS_JOINDRE_ID=${{ vars.SPIP_RUBRIQUE_CONTACT_ARTICLE_NOUS_JOINDRE_ID }}
            SPIP_RUBRIQUE_CONTACT_ARTICLE_LACLASSE_ID=${{ vars.SPIP_RUBRIQUE_CONTACT_ARTICLE_LACLASSE_ID }}
            SPIP_RUBRIQUE_CONTACT_ARTICLE_RESEAUX_SOCIAUX_ID=${{ vars.SPIP_RUBRIQUE_CONTACT_ARTICLE_RESEAUX_SOCIAUX_ID }}
